spring.application.name=sinnitto-example
spring.profiles.include=dev
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.profiles.active=dev
spring.data.redis.host=sinitto.site
spring.data.redis.port=6379
spring.data.redis.password=sinitto
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.h2.console.enabled=false
